### ISSUE TITLE
Biome overwritten by undergarden mod

### ISSUE THREAD

**Issue by NekoSpirits** [UnRealModding/JAVD#11]
Playing in the Direwolf20 1.16 mod pack, before updating, the void dimension was "The Void" biome after the update was a "SmogStem Forest" from the mod "The Undergarden". It looks like that mod overwrites "The Void" biome. Side effects of the overwrite are very weird, mobs from that mod spawn in the void dimension and blow things up like creepers, but possibly only client-side as the blocks that get destroyed are desynced and come back after updating the blocks. Not sure if this is a JAVD bug or an Undergarden bug.

**Comment by UnRealDinnerbone** [comment]
The same issue happened in the update with the Mining Dimension (  https://github.com/FTBTeam/FTB-Presents-Direwolf20-1.16/issues/99 )
guessing it the same issue ( https://github.com/quek04/The-Undergarden/issues/65 )
