### ISSUE TITLE
feature request: start in void on custom platform

### ISSUE THREAD

**Issue by Tenchu98** [UnRealModding/JAVD#14]
Would it be possible to add functionality similar to the abandoned void island control mod?

I am looking for a 1.16.4 mod that allows starting on a custom structure in the void world, and wasn't sure if this was withing the scope of your mod.

**Comment by UnRealDinnerbone** [comment]
Yea I really don't want to add this to my mod, I might happen in the feature but right now I'm trying to keep this mod as simple as possible
