### ISSUE TITLE
How to change settings

### ISSUE THREAD

**Issue by Goten87** [UnRealModding/JAVD#15]
How do I change the settings
I want to set the option to have players have there own dim and not shared can you tell me how to do that 
Also how to change the generation of the platform it’s generating at Y:1 and I want to to be higher is there a way to do that

**Comment by UnRealDinnerbone** [comment]
Oh I need to fix that at y 1, but due to how dimensions work not in 1.16.3+ I cant have configs per player dimensions I updated curseforge to show that

**Comment by Goten87** [comment]
maby tell it that its not in yet or the version its in
is that from 1.16.5 or something ?

**Comment by UnRealDinnerbone** [comment]
There no config for 1.16.3+ I added a thing on the curseforge page to say that there only for 1.15
