### ISSUE TITLE
Invalid world ID set

### ISSUE THREAD

**Issue by pennyvise1** [UnRealModding/JAVD#16]
Updated direwolf to 1.16.5 and get this when I try to go to my void dim

![image](https://user-images.githubusercontent.com/6539792/106899395-28ce1500-66aa-11eb-9bee-a3d93b158965.png)

I can't find anywhere in the config to define a world ID and am not even completely versed on how this works on 1.16 yet

**Comment by pennyvise1** [comment]
Fixed by deleting the javd dir in dimensions, starting the server and then copying the old dir back and starting again

**Comment by UnRealDinnerbone** [comment]
This is most likely due to how Unstable dimensions are in 1.16.3+ I really don't know what I can do about it.
 I should fix that message through in-game as it clearly saying witch part is an error in the code.
