### ISSUE TITLE
Solar neutron activator 

### ISSUE THREAD

**Issue by MrLeonBrooks** [UnRealModding/JAVD#17]
Although placed in 'always sunny dimension'(just another void dimension) the solar neutron activator does not register it being daytime. running the latest version(2.5.45) on the latest direwolf20 pack(1.6.1)  on forge 1.16.5.

**Comment by MrLeonBrooks** [comment]
im dumb and didnt see you already addressed this.  problem is it still wont work after setting fixed_time false

  "name": "javd:void",
  "ultrawarm": false,
  "natural": false,
  "coordinate_scale": 1,
  "has_skylight": true,
  "has_ceiling": false,
  "ambient_light": 0.00,
  "fixed_time": false,
  "piglin_safe": true,
  "bed_works": true,
  "respawn_anchor_works": false,
  "has_raids": true,
  "logical_height": 256,
  "infiniburn": "minecraft:infiniburn_overworld"

**Comment by UnRealDinnerbone** [comment]
Im guessing the issue is related to this https://github.com/UnRealDinnerbone/JAVD/issues/9#issuecomment-759184905
