### ISSUE TITLE
Config options for a more overworld-like void dimension?

### ISSUE THREAD

**Issue by marc-cwm** [UnRealModding/JAVD#19]
Is it possible to get config options to normalize the void dimension a bit?

Potentially to enable an overworld skybox and a day/night cycle?

Making Rain and weather a possibility?

And, an option to allow sleeping in beds?

**Comment by UnRealDinnerbone** [comment]
This can be done with a datapack

**Comment by marc-cwm** [comment]
Realistically, the whole mod could be done with a datapack, I think.

I appreciate your response, but my suggestion was hoping for something a bit more granular and easier to modify.
