### ISSUE TITLE
Teleporting back from void dim

### ISSUE THREAD

**Issue by Sunekaer** [UnRealModding/JAVD#2]
So I was expecting when I teleported back to go back to my portal block in the overworld, but I ended up at my bed?

If I remove my bed and I teleport back from void dim I then end up at spawn...

If I enable "allowRespawn" and sets my spawn in void dim and want to go back to my overworld base I end up at spawn again far from my base

**Comment by UnRealDinnerbone** [comment]
I will look into this tomorrow

**Comment by UnRealDinnerbone** [comment]
Ok, I changed it, that portal will now send you back to the portal you enter the void from
