### ISSUE TITLE
Mob Spawn

### ISSUE THREAD

**Issue by Tdlreis** [UnRealModding/JAVD#25]
I tried to do a vanilla stile mob farm, but the only mob that is is spawning is slimes, I don't know if there is any config that I can change or if the void dimension simply doesn't allow natural hostile mob spawning. By the way I am playing in Minecraft 1.16.5

**Comment by Tdlreis** [comment]
Sorry for opening and closing, first time using issues on GitHub

**Comment by UnRealDinnerbone** [comment]
The biome json defined with mobs can spawn, you have to use a datapack or a mod like KubeJS to change the spawns in the biome https://github.com/UnRealModding/JAVD/blob/9fcbbe2660ce44084e7d959b253e805cf47b9db2/src/main/resources/data/javd/worldgen/biome/void.json#L24
