### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by LadoAlpha** [UnRealModding/JAVD#28]
Hello! 

How to fix this error on my server? I use your mod along with the Beyond Earth mod.

![2022-01-24_14 20 45](https://user-images.githubusercontent.com/98343690/150833648-3ee91143-c267-48a1-b7b9-50c5dd3d0849.png)

**Comment by UnRealDinnerbone** [comment]
What version of the mod?

**Comment by LadoAlpha** [comment]
1.18.1

**Comment by UnRealDinnerbone** [comment]
mod version not version of minecraft

**Comment by LadoAlpha** [comment]
JAVD-2.8.0-build.52+mc1.18.1.jar
Beyond-Earth-1.18.1-5.9c.jar

**Comment by UnRealDinnerbone** [comment]
does this happen after you replace the portal?

**Comment by LadoAlpha** [comment]
No. Actually, I put it on the ground and couldn't enter the dimension. This only happens on the server. In singleplayer it works normally.

**Comment by UnRealDinnerbone** [comment]
I look into it

**Comment by LadoAlpha** [comment]
Hi again! Any progress?

**Comment by UnRealDinnerbone** [comment]
New version should be out on curseforge soon, that should fix this
