### ISSUE TITLE
1.16.3 - Stuck in Wall after teleporting back

### ISSUE THREAD

**Issue by realTIMematrix** [UnRealModding/JAVD#5]
Hi,

still using only Forge 34.1.25, Minecraft 1.16.3, JAVD 2.3.2 and JEI.

When I'm in creative mode, grab your void block, place it down and teleport to the void world works fine.

Teleporting back I'm stuck in a wall down at bedrock level in the overworld.

What I'm doing wrong?

**Comment by UnRealDinnerbone** [comment]
Yha I know, planing at look at the soon. It is a bug

**Comment by UnRealDinnerbone** [comment]
Hopefully the new versions on curseforge fix your issue
