### ISSUE TITLE
[1.16.4] Cannot Shift + R-Click Anything

### ISSUE THREAD

**Issue by TwilightPSN** [UnRealModding/JAVD#6]
With this mod installed, we are not able to Shift + R-Click interact with anything. Here is the error being thrown. Upon removing the mod all works just fine.

https://gist.github.com/TwilightPSN/57b022f41d0bc8834fbc13fcd0e76c6b

**Comment by UnRealDinnerbone** [comment]
Fixed in lastest commit should be on curseforge soon
