### ISSUE TITLE
No types have been added to Biome javd:the_void, types have been assigned on a best-effort guess: could not guess types

### ISSUE THREAD

**Issue by ValentinJD-Pro** [UnRealModding/JAVD#7]
I think it's pretty clear : (in the last 1.15.2 version)

"No types have been added to Biome javd:the_void, types have been assigned on a best-effort guess: could not guess types"

is spammed in the logs, whereas forge should guess a type of biome if not specified in the code of the mod (but it can't find anything as it's a void dimension)

**Comment by ValentinJD-Pro** [comment]
Hello, is it solved ? i see no updates ... ?

**Comment by UnRealDinnerbone** [comment]
Im sorry this is for 1.15 witch I no longer support

**Comment by ValentinJD-Pro** [comment]
:( is there no way to have a custom quick fixed version even with no console outputs at all ? I'm opening a big server but those log spams are really causing problems...
