### ISSUE TITLE
Why global illumination?

### ISSUE THREAD

**Issue by Bellwar** [UnRealModding/JAVD#8]
I was just wondering why did you make it so that there is light everywhere. I wanted to create a mob farm in the void and since there is light everywhere, for example, Mechanical dirt doesn't want to spawn any mobs, even when I create closed room.

**Comment by UnRealDinnerbone** [comment]
I wanted it so you don't need to worry about lighting up your base, I can look into fixing mob spawns

**Comment by Bellwar** [comment]
It just, being a void, the mob spawn is bigger so its nice place for it. But I get your point.

**Comment by cpebud** [comment]
I had the same idea. I built a falling mob spawner, and the light levels read 0 inside, but still no mobs are spawning

**Comment by UnRealDinnerbone** [comment]
I take a look at this issue monday

**Comment by UnRealDinnerbone** [comment]
> I had the same idea. I built a falling mob spawner, and the light levels read 0 inside, but still no mobs are spawning

What do you mean falling mob spawner? is this an item from a mod or something? if you mean like a dark room where mobs spawn and then fall down no that won't work, as there no mob spawn in the void world, pushing fix out soon to allow other mods spawners and such to work
