### ISSUE TITLE
Mekanism solars not working in void dimension

### ISSUE THREAD

**Issue by finalsabbath** [UnRealModding/JAVD#9]
Version : 2.5.42
MC Version : 1.16.4
Modpack : Direwolf20 1.20

Poked though Mekanism page and guessing one of these checks is failing:

`    private boolean canFunction() {
        // Sort out if the solar neutron activator can see the sun; we no longer check if it's raining here,
        // since under the new rules, we can still function when it's raining, albeit at a significant penalty.
        boolean seesSun = world.isDaytime() && world.canBlockSeeSky(pos.up()) && world.getDimensionType().hasSkyLight();
        return seesSun && MekanismUtils.canFunction(this);
    }`

This is for the solar neutron activator since that was originally what I was trying to get working but same issue for other Mekanism solars.

**Comment by finalsabbath** [comment]
Guessing this is related to https://github.com/UnRealDinnerbone/JAVD/issues/4

**Comment by UnRealDinnerbone** [comment]
This is going to take a bit more work to fix, I will look into fixing it within a week or so

**Comment by finalsabbath** [comment]
Sounds good, thanks!

**Comment by NekoSpirits** [comment]
Same for the solar panels from "Powah". It also looks like the sky is darker so it could be the rain check? Daylight sensor gives off a signal of 12 so using the chart below the only thing that lines up with permanent noon is rain.

![image](https://user-images.githubusercontent.com/20034469/104393055-8343dd80-5511-11eb-8e3a-788f622eeaa6.png)

**Comment by UnRealDinnerbone** [comment]
So the issue is the way the isDaytime() is checked is a bit weird for some reason if your world has a fixed time (Like the Void world does) it returns false. I could change this with a Mixin but I prefer not to. (Will have an update later on what I will do about this)

**Comment by UnRealDinnerbone** [comment]
Looking the way to "fix" this would be to change the "fixed_time" in data/javd/dimension_type/void.json to false, only down side would be that the  world have a daylight cycle then

**Comment by UnRealDinnerbone** [comment]
Well after thinking about I really don't want to mixin into the check for this so if you really want to be able to use stuff that calls isDaytime() change "fixed_time" in data/javd/dimension_type/void.json  to false
